/**
 * Extra surface forms per taxonomy leaf, beyond the leaf's own Turkish/Chinese/English labels:
 * English plurals and alternate spellings, plus the most common German, Russian, Japanese,
 * Korean, Indonesian and Thai words seen on the beta markets (Amazon DE, Ozon, Rakuten,
 * Coupang, Tokopedia, Lazada). Latin forms are matched as whole words after Turkish folding;
 * other scripts as substrings. Keys are taxonomy leaf keys (slug of the Turkish label).
 */
export const LEAF_SYNONYMS: Record<string, string[]> = {
  "kablosuz-kulaklik": ["earbuds", "earbud", "tws", "true wireless", "bluetooth earphones", "wireless earphones", "in-ear", "蓝牙耳机", "无线蓝牙耳机", "tws耳机", "真无线耳机", "ワイヤレスイヤホン", "이어폰", "наушники беспроводные", "kabellose kopfhörer", "earphone bluetooth"],
  "kulak-ustu-kulaklik": ["over ear headphones", "over-ear", "headphones wireless", "ヘッドホン", "헤드폰", "наушники накладные", "over-ear kopfhörer"],
  kulaklik: ["earphones", "earphone", "headphone", "headset", "イヤホン", "наушники", "kopfhörer", "headphone"],
  "akilli-saat": ["smartwatch", "smart watches", "スマートウォッチ", "스마트워치", "смарт-часы", "смарт часы", "jam tangan pintar"],
  "akilli-bileklik": ["smart band", "fitness band", "activity tracker", "фитнес браслет", "smart bracelet"],
  powerbank: ["powerbank", "power banks", "portable charger", "モバイルバッテリー", "보조배터리", "повербанк", "внешний аккумулятор"],
  "bluetooth-hoparlor": ["bluetooth speakers", "wireless speaker", "portable speaker", "スピーカー", "블루투스 스피커", "колонка", "lautsprecher"],
  "sarj-adaptoru": ["chargers", "power adapter", "wall charger", "usb charger", "gan charger", "充電器", "충전기", "зарядное устройство", "ladegerät"],
  "sarj-kablosu": ["usb cable", "charging cables", "usb-c cable", "type-c cable", "lightning cable", "ケーブル", "кабель", "ladekabel"],
  "kablosuz-sarj": ["wireless chargers", "qi charger", "magsafe charger", "ワイヤレス充電器", "беспроводная зарядка"],
  webcam: ["web camera", "webcams", "ウェブカメラ", "웹캠", "веб-камера"],
  "mekanik-klavye": ["mechanical keyboards", "gaming keyboard", "keyboard", "メカニカルキーボード", "키보드", "клавиатура", "tastatur"],
  "kablosuz-mouse": ["wireless mice", "mouse", "gaming mouse", "マウス", "마우스", "мышь", "maus"],
  "oyuncu-kulakligi": ["gaming headsets", "gaming headphones", "ゲーミングヘッドセット", "게이밍 헤드셋"],
  mikrofon: ["microphones", "mic", "マイク", "마이크", "микрофон", "mikrofon"],
  "telefon-kilifi": ["phone cases", "phone cover", "iphone case", "samsung case", "スマホケース", "폰케이스", "чехол для телефона", "handyhülle", "hülle"],
  "ekran-koruyucu": ["screen protectors", "tempered glass", "保護フィルム", "защитное стекло", "panzerglas"],
  "telefon-tutucu": ["phone holders", "phone stand", "phone mount", "держатель для телефона", "handyhalterung"],
  "akilli-priz": ["smart plugs", "wifi plug", "smart socket", "умная розетка", "smarte steckdose"],
  "ip-kamera": ["ip cameras", "security camera", "wifi camera", "cctv camera", "防犯カメラ", "камера видеонаблюдения", "überwachungskamera"],
  drone: ["drones", "quadcopter", "ドローン", "드론", "дрон", "drohne"],
  "aksiyon-kamerasi": ["action cameras", "action cam", "アクションカメラ", "экшн камера"],
  "usb-bellek": ["flash drive", "usb stick", "pendrive", "usb drive", "флешка", "usb-stick"],
  "tasinabilir-ssd": ["external ssd", "portable ssd", "nvme enclosure", "внешний ssd"],
  telefon: ["smartphones", "mobile phone", "cell phone", "スマートフォン", "스마트폰", "смартфон"],
  tablet: ["tablets", "タブレット", "태블릿", "планшет"],
  laptop: ["laptops", "notebook pc", "ノートパソコン", "노트북", "ноутбук"],
  monitor: ["monitors", "モニター", "모니터", "монитор", "bildschirm"],
  pil: ["batteries", "aa battery", "rechargeable battery", "電池", "건전지", "батарейки", "batterie", "akku"],
  ampul: ["light bulbs", "led bulb", "電球", "лампочка", "glühbirne"],
  priz: ["power strips", "extension cord", "extension lead", "удлинитель", "steckdosenleiste"],
  "laptop-standi": ["laptop stands", "notebook stand", "подставка для ноутбука"],
  "usb-hub": ["usb hubs", "docking station", "usb-c hub", "ドッキングステーション"],
  "mouse-pad": ["mouse pads", "mousepad", "desk mat", "коврик для мыши"],
  "barkod-okuyucu": ["barcode scanners", "qr scanner", "сканер штрих-кода"],
  "wi-fi-router": ["routers", "wifi routers", "mesh wifi", "роутер"],
  "projeksiyon-cihazi": ["projectors", "mini projector", "プロジェクター", "프로젝터", "проектор", "beamer"],
  termos: ["thermos", "vacuum flask", "insulated bottle", "insulated tumbler", "tumbler", "水筒", "텀블러", "термос", "thermosflasche"],
  "su-sisesi": ["water bottles", "sports bottle", "bottle", "botol minum", "бутылка для воды", "trinkflasche"],
  "yapismaz-tava": ["frying pan", "non stick pan", "skillet", "фрайпан", "сковорода", "pfanne"],
  "tencere-seti": ["cookware sets", "pot set", "pots and pans", "набор кастрюль", "topfset"],
  "bicak-seti": ["knife sets", "kitchen knife", "chef knife", "包丁", "набор ножей", "messerset"],
  "masaustu-duzenleyici": ["desk organizers", "desktop organizer", "органайзер"],
  "hava-nemlendirici": ["humidifiers", "加湿器", "가습기", "увлажнитель", "luftbefeuchter"],
  "aroma-difuzoru": ["diffusers", "essential oil diffuser", "アロマディフューザー", "аромадиффузор"],
  "led-serit": ["led strips", "led strip light", "light strip", "led light strip", "ledテープ", "светодиодная лента", "led streifen"],
  "masa-lambasi": ["desk lamps", "table lamp", "reading lamp", "デスクライト", "настольная лампа", "schreibtischlampe"],
  "gece-lambasi": ["night lights", "ночник", "nachtlicht"],
  "duvar-saati": ["wall clocks", "掛け時計", "настенные часы", "wanduhr"],
  yastik: ["pillows", "cushion", "枕", "베개", "подушка", "kissen", "bantal"],
  "nevresim-takimi": ["bedding sets", "duvet cover set", "sheet set", "постельное белье", "bettwäsche"],
  battaniye: ["blankets", "throw blanket", "fleece blanket", "毛布", "담요", "плед", "одеяло", "decke", "selimut"],
  perde: ["curtains", "blackout curtains", "カーテン", "커튼", "шторы", "vorhang"],
  hali: ["rugs", "carpet", "area rug", "ラグ", "카펫", "ковер", "teppich", "karpet"],
  havlu: ["towels", "bath towel", "タオル", "수건", "полотенце", "handtuch", "handuk"],
  "camasir-sepeti": ["laundry baskets", "laundry hamper", "корзина для белья", "wäschekorb"],
  aski: ["hangers", "clothes hangers", "coat hanger", "ハンガー", "옷걸이", "вешалки", "kleiderbügel", "gantungan baju"],
  "cop-kovasi": ["trash cans", "garbage bin", "waste bin", "ゴミ箱", "мусорное ведро", "mülleimer"],
  mum: ["candles", "candle", "キャンドル", "свеча", "kerze"],
  vazo: ["vases", "花瓶", "ваза"],
  yorgan: ["duvets", "comforter", "quilt", "одеяло", "bettdecke"],
  "mobilya-koltuk": ["sofas", "couch", "sectional", "диван", "sofa"],
  airfryer: ["air fryers", "airfryer", "ノンフライヤー", "에어프라이어", "аэрогриль", "heißluftfritteuse"],
  blender: ["blenders", "smoothie maker", "ミキサー", "блендер", "mixer"],
  "kahve-makinesi": ["coffee machines", "espresso machine", "coffee makers", "コーヒーメーカー", "커피머신", "кофемашина", "kaffeemaschine"],
  "elektrikli-kettle": ["kettles", "electric kettles", "電気ケトル", "전기포트", "чайник электрический", "wasserkocher"],
  "mutfak-tartisi": ["kitchen scales", "food scale", "кухонные весы", "küchenwaage"],
  "pirinc-pisirici": ["rice cookers", "炊飯器", "밥솥", "рисоварка", "reiskocher", "rice cooker"],
  mikrodalga: ["microwaves", "microwave oven", "電子レンジ", "микроволновка", "mikrowelle"],
  "robot-supurge": ["robot vacuums", "robotic vacuum", "robot vacuum cleaner", "扫地机器人", "ロボット掃除機", "로봇청소기", "робот-пылесос", "saugroboter"],
  "kablosuz-supurge": ["cordless vacuums", "stick vacuum", "cordless vacuum cleaner", "無線掃除機", "无线吸尘器", "무선청소기", "беспроводной пылесос", "akku staubsauger"],
  "el-supurgesi": ["handheld vacuums", "hand vacuum", "ручной пылесос"],
  "buharli-utu": ["steam irons", "garment steamer", "iron", "アイロン", "утюг", "bügeleisen", "setrika"],
  vantilator: ["fans", "desk fan", "tower fan", "扇風機", "선풍기", "вентилятор", "ventilator", "kipas angin"],
  isitici: ["heaters", "space heater", "ヒーター", "обогреватель", "heizlüfter"],
  "hava-temizleyici": ["air purifiers", "空気清浄機", "공기청정기", "очиститель воздуха", "luftreiniger"],
  "sac-kurutma-makinesi": ["hair dryers", "blow dryer", "ドライヤー", "드라이기", "фен", "haartrockner", "föhn"],
  elbise: ["dresses", "ワンピース", "원피스", "платье", "kleid", "gaun"],
  bluz: ["blouses", "блузка", "bluse"],
  etek: ["skirts", "スカート", "스커트", "юбка", "rock"],
  hirka: ["cardigans", "カーディガン", "кардиган", "strickjacke"],
  kazak: ["sweaters", "pullover", "knitwear", "jumper", "セーター", "니트", "свитер", "pullover"],
  tayt: ["leggings", "yoga pants", "レギンス", "레깅스", "леггинсы"],
  sort: ["shorts", "ショートパンツ", "шорты"],
  pijama: ["pajama", "pyjamas", "sleepwear", "パジャマ", "잠옷", "пижама", "schlafanzug"],
  mayo: ["swimsuits", "swimwear", "bikini", "水着", "수영복", "купальник", "badeanzug"],
  "spor-sutyeni": ["sports bras", "спортивный бра", "sport-bh"],
  "polo-yaka": ["polo shirts", "polo", "ポロシャツ", "поло"],
  gomlek: ["shirts", "dress shirt", "シャツ", "셔츠", "рубашка", "hemd", "kemeja"],
  esofman: ["tracksuits", "sweatpants", "jogger", "joggers", "спортивный костюм", "trainingsanzug", "jogginghose"],
  "takim-elbise": ["suits", "blazer", "スーツ", "костюм", "anzug"],
  boxer: ["boxers", "boxer shorts", "trunks", "ボクサーパンツ", "боксеры"],
  "deri-ceket": ["leather jackets", "leather coat", "кожаная куртка", "lederjacke"],
  "spor-ayakkabi": ["sneakers", "trainers", "sports shoes", "スニーカー", "운동화", "кроссовки", "turnschuhe", "sepatu olahraga"],
  "kosu-ayakkabisi": ["running shoes", "ランニングシューズ", "러닝화", "беговые кроссовки", "laufschuhe"],
  bot: ["boots", "ankle boots", "ブーツ", "부츠", "ботинки", "stiefel"],
  cizme: ["knee high boots", "сапоги"],
  "topuklu-ayakkabi": ["heels", "high heels", "pumps", "ハイヒール", "туфли на каблуке"],
  babet: ["flats", "ballet flats", "балетки"],
  sandalet: ["sandals", "サンダル", "샌들", "сандалии", "sandalen"],
  terlik: ["slippers", "slides", "flip flops", "スリッパ", "슬리퍼", "тапочки", "hausschuhe", "sandal jepit"],
  loafer: ["loafers", "ローファー", "лоферы"],
  "ayakkabi-tabanligi": ["insoles", "shoe inserts", "стельки", "einlegesohlen"],
  "sirt-cantasi": ["backpacks", "rucksack", "バックパック", "リュック", "백팩", "рюкзак", "rucksack", "tas ransel"],
  valiz: ["suitcases", "luggage", "trolley", "carry-on", "スーツケース", "캐리어", "чемодан", "koffer", "koper"],
  cuzdan: ["wallets", "財布", "지갑", "кошелек", "geldbörse", "portemonnaie", "dompet"],
  "capraz-canta": ["crossbody bags", "sling bag", "messenger bag", "сумка через плечо", "umhängetasche"],
  "tote-canta": ["tote bags", "shopper", "トートバッグ", "сумка-шоппер"],
  "bel-cantasi": ["waist bags", "fanny pack", "belt bag", "bum bag", "поясная сумка", "bauchtasche"],
  "omuz-cantasi": ["shoulder bags", "handbag", "purse", "ショルダーバッグ", "숄더백", "сумка", "handtasche", "tas selempang"],
  "spor-cantasi": ["gym bags", "duffel bag", "sports bag", "спортивная сумка", "sporttasche"],
  "makyaj-cantasi": ["makeup bags", "cosmetic bag", "toiletry bag", "косметичка", "kosmetiktasche"],
  kartlik: ["card holders", "card wallet", "картхолдер", "kartenetui"],
  "seyahat-organizeri": ["packing cubes", "travel organizer", "органайзер для путешествий"],
  "beslenme-cantasi": ["lunch bags", "lunch box", "cooler bag", "ランチバッグ", "ланч бокс", "kühltasche"],
  "okul-cantasi": ["school bags", "school backpack", "школьный рюкзак", "schulranzen"],
  canta: ["bags", "ハンドバッグ", "가방", "сумки", "tasche", "tas"],
  "gunes-gozlugu": ["sunglasses", "sunglass", "shades", "サングラス", "선글라스", "солнцезащитные очки", "sonnenbrille", "kacamata hitam"],
  "mavi-isik-gozlugu": ["blue light blocking glasses", "computer glasses", "очки для компьютера"],
  "kol-saati": ["wristwatches", "watches", "watch men", "watch women", "腕時計", "손목시계", "наручные часы", "armbanduhr", "jam tangan"],
  "saat-kordonu": ["watch bands", "watch straps", "apple watch band", "ремешок для часов", "uhrenarmband"],
  kolye: ["necklaces", "pendant", "chain necklace", "ネックレス", "목걸이", "ожерелье", "колье", "halskette", "kalung"],
  bileklik: ["bracelets", "bangle", "ブレスレット", "팔찌", "браслет", "armband", "gelang"],
  kupe: ["earrings", "studs", "hoop earrings", "ピアス", "귀걸이", "серьги", "ohrringe", "anting"],
  yuzuk: ["rings", "指輪", "반지", "кольцо", "ring", "cincin"],
  kemer: ["belts", "leather belt", "ベルト", "벨트", "ремень", "gürtel", "sabuk"],
  sapka: ["hats", "cap", "baseball cap", "bucket hat", "キャップ", "帽子", "모자", "кепка", "шляпа", "mütze", "topi"],
  bere: ["beanies", "knit hat", "ニット帽", "шапка", "beanie"],
  atki: ["scarves", "scarf", "shawl", "マフラー", "스카프", "шарф", "schal", "syal"],
  eldiven: ["gloves", "mittens", "手袋", "장갑", "перчатки", "handschuhe", "sarung tangan"],
  kravat: ["ties", "necktie", "ネクタイ", "галстук", "krawatte"],
  "sac-tokasi": ["hair clips", "hair claw", "claw clip", "scrunchie", "заколка", "haarspange"],
  semsiye: ["umbrellas", "傘", "우산", "зонт", "regenschirm", "payung"],
  anahtarlik: ["keychains", "keyring", "key chain", "キーホルダー", "키링", "брелок", "schlüsselanhänger"],
  "yuz-serumu": ["serums", "face serum", "vitamin c serum", "hyaluronic serum", "美容液", "세럼", "сыворотка"],
  "nemlendirici-krem": ["moisturizers", "face cream", "moisturising cream", "保湿クリーム", "крем для лица", "feuchtigkeitscreme"],
  "gunes-kremi": ["sunscreens", "spf", "sun cream", "日焼け止め", "선크림", "солнцезащитный крем", "sonnencreme"],
  "yuz-maskesi": ["sheet mask", "face masks", "clay mask", "フェイスマスク", "마스크팩", "маска для лица"],
  "temizleme-jeli": ["cleansers", "face wash", "facial cleanser", "洗顔", "클렌저", "гель для умывания"],
  "makyaj-fircasi": ["makeup brushes", "brush set", "メイクブラシ", "кисти для макияжа"],
  ruj: ["lipsticks", "lip gloss", "lip tint", "口紅", "립스틱", "помада", "lippenstift"],
  maskara: ["mascaras", "マスカラ", "тушь"],
  "far-paleti": ["eyeshadow palettes", "eyeshadow", "палетка теней", "lidschatten"],
  oje: ["nail polish", "gel polish", "nail gel", "ネイル", "лак для ногтей", "nagellack"],
  parfum: ["perfumes", "fragrance", "eau de parfum", "cologne", "香水", "향수", "духи", "parfüm", "parfum"],
  "sac-duzlestirici": ["hair straighteners", "flat iron", "ヘアアイロン", "고데기", "выпрямитель", "glätteisen"],
  "sac-masasi": ["curling irons", "curling wand", "hair curler", "плойка", "lockenstab"],
  "sac-kesme-makinesi": ["hair clippers", "trimmer", "beard trimmer", "バリカン", "машинка для стрижки", "haarschneider"],
  "tiras-makinesi": ["electric shavers", "razor", "shaver", "シェーバー", "면도기", "электробритва", "rasierer"],
  "epilasyon-cihazi": ["ipl hair removal", "epilator", "laser hair removal", "эпилятор", "epilierer"],
  "elektrikli-dis-fircasi": ["electric toothbrushes", "sonic toothbrush", "電動歯ブラシ", "전동칫솔", "электрическая зубная щетка", "elektrische zahnbürste"],
  "makyaj-aynasi": ["makeup mirrors", "vanity mirror", "led mirror", "зеркало для макияжа", "kosmetikspiegel"],
  "masaj-tabancasi": ["massage guns", "percussion massager", "массажный пистолет", "massagepistole"],
  "tansiyon-aleti": ["blood pressure monitors", "bp monitor", "血圧計", "тонометр", "blutdruckmessgerät"],
  "ates-olcer": ["thermometers", "infrared thermometer", "体温計", "термометр"],
  "pulse-oksimetre": ["pulse oximeters", "oximeter", "пульсоксиметр"],
  "akilli-tarti": ["smart scales", "body scale", "bathroom scale", "体重計", "умные весы", "körperwaage"],
  "boyun-masaj-aleti": ["neck massagers", "массажер для шеи", "nackenmassagegerät"],
  "ortopedik-yastik": ["memory foam pillow", "orthopedic pillows", "ортопедическая подушка"],
  dizlik: ["knee braces", "knee support", "knee sleeve", "наколенник", "kniebandage"],
  maske: ["face masks disposable", "kn95", "ffp2", "surgical mask", "медицинская маска", "mundschutz"],
  "yoga-mati": ["yoga mats", "exercise mat", "ヨガマット", "요가매트", "коврик для йоги", "yogamatte", "matras yoga"],
  dambil: ["dumbbells", "dumbbell set", "ダンベル", "덤벨", "гантели", "hanteln"],
  "direnc-bandi": ["resistance bands", "exercise bands", "фитнес резинки", "fitnessband"],
  "atlama-ipi": ["jump ropes", "skipping rope", "скакалка", "springseil"],
  kettlebell: ["kettlebells", "гиря"],
  "kosu-bandi": ["treadmills", "walking pad", "беговая дорожка", "laufband"],
  "kondisyon-bisikleti": ["exercise bikes", "spin bike", "велотренажер", "heimtrainer"],
  "pilates-topu": ["exercise balls", "yoga ball", "фитбол", "gymnastikball"],
  "kamp-cadiri": ["tents", "camping tent", "テント", "텐트", "палатка", "zelt", "tenda"],
  "uyku-tulumu": ["sleeping bags", "寝袋", "침낭", "спальный мешок", "schlafsack"],
  "kamp-sandalyesi": ["camping chairs", "folding chair", "складной стул", "campingstuhl"],
  "kafa-lambasi": ["headlamps", "head torch", "ヘッドライト", "налобный фонарь", "stirnlampe"],
  durbun: ["binoculars", "双眼鏡", "бинокль", "fernglas"],
  "bisiklet-kaski": ["bike helmets", "cycling helmet", "bicycle helmet", "велошлем", "fahrradhelm"],
  scooter: ["scooters", "kick scooter", "самокат", "roller"],
  kaykay: ["skateboards", "longboard", "скейтборд"],
  paten: ["roller skates", "inline skates", "ролики", "rollschuhe"],
  "yuzucu-gozlugu": ["swim goggles", "swimming goggles", "очки для плавания", "schwimmbrille"],
  "futbol-topu": ["soccer ball", "footballs", "футбольный мяч", "fußball"],
  "basketbol-topu": ["basketballs", "баскетбольный мяч"],
  raket: ["rackets", "racquet", "badminton racket", "tennis racket", "ракетка", "schläger"],
  "motosiklet-kaski": ["motorcycle helmets", "motorbike helmet", "full face helmet", "modular helmet", "open face helmet", "flip up helmet", "ヘルメット バイク", "мотошлем", "motorradhelm", "helm motor"],
  kask: ["helmets", "ヘルメット", "헬멧", "шлем", "helm"],
  "motosiklet-eldiveni": ["motorcycle gloves", "riding gloves", "мотоперчатки", "motorradhandschuhe"],
  "motosiklet-montu": ["motorcycle jackets", "riding jacket", "мотокуртка", "motorradjacke"],
  "motosiklet-telefon-tutucu": ["motorcycle phone mount", "bike phone holder", "держатель для телефона на мотоцикл"],
  "motosiklet-cantasi": ["motorcycle bags", "tank bag", "saddlebag", "мотосумка"],
  "motosiklet-kilidi": ["motorcycle locks", "disc lock", "мотозамок"],
  "fren-balatasi": ["brake pads", "тормозные колодки", "bremsbeläge"],
  "elektrikli-scooter": ["electric scooters", "e-scooter", "電動キックボード", "전동킥보드", "электросамокат", "e-roller"],
  "elektrikli-bisiklet": ["electric bikes", "e-bike", "ebike", "電動自転車", "электровелосипед"],
  "arac-kamerasi": ["dash cams", "dashcam", "car camera", "ドライブレコーダー", "블랙박스", "видеорегистратор", "dashcam"],
  "arac-telefon-tutucu": ["car phone holders", "car mount", "автодержатель", "handyhalterung auto"],
  "arac-supurgesi": ["car vacuums", "car vacuum cleaner", "автопылесос", "autostaubsauger"],
  "oto-koltuk-kilifi": ["car seat covers", "чехлы на сиденья", "autositzbezug"],
  "aku-takviye": ["jump starters", "booster", "пусковое устройство", "starthilfe"],
  "lastik-pompasi": ["tire inflators", "air pump", "tyre inflator", "компрессор автомобильный", "luftpumpe"],
  "arac-sarj-cihazi": ["car chargers", "usb car charger", "автомобильное зарядное", "kfz ladegerät"],
  "led-far-ampulu": ["led headlight bulbs", "h4 led", "h7 led", "led лампы", "led scheinwerfer"],
  "oto-paspasi": ["car mats", "floor mats", "автоковрики", "fußmatten auto"],
  "direksiyon-kilifi": ["steering wheel covers", "оплетка на руль", "lenkradbezug"],
  "arac-kokusu": ["car air fresheners", "car perfume", "ароматизатор в машину", "autoduft"],
  silecek: ["wiper blades", "windshield wipers", "дворники", "scheibenwischer"],
  far: ["headlights", "headlamp assembly", "фары", "scheinwerfer"],
  lastik: ["tires", "tyres", "car tyre", "шины", "reifen"],
  "obd-tarayici": ["obd2 scanner", "obd scanner", "diagnostic tool", "диагностический сканер", "obd2 diagnosegerät"],
  "geri-gorus-kamerasi": ["backup cameras", "reverse camera", "rear view camera", "камера заднего вида", "rückfahrkamera"],
  "sarjli-matkap": ["cordless drills", "drill driver", "impact driver", "電動ドリル", "шуруповерт", "дрель", "akkuschrauber", "bohrmaschine"],
  "alet-seti": ["tool sets", "tool kit", "набор инструментов", "werkzeugset", "werkzeugkoffer"],
  "serit-metre": ["tape measures", "measuring tape", "рулетка", "maßband"],
  "lazer-hizalayici": ["laser levels", "лазерный уровень", "laser wasserwaage"],
  "elektrikli-tornavida": ["electric screwdrivers", "электроотвертка", "akku-schraubendreher"],
  "silikon-tabancasi": ["glue guns", "hot glue gun", "клеевой пистолет", "heißklebepistole"],
  multimetre: ["multimeters", "мультиметр", "multimeter"],
  "el-feneri": ["flashlights", "torch", "led torch", "懐中電灯", "손전등", "фонарь", "taschenlampe", "senter"],
  "anahtar-seti": ["wrench sets", "socket set", "spanner set", "набор ключей", "schraubenschlüssel"],
  merdiven: ["ladders", "step ladder", "стремянка", "leiter"],
  "avuc-taslama": ["angle grinders", "болгарка", "winkelschleifer"],
  "kaynak-makinesi": ["welding machines", "welder", "сварочный аппарат", "schweißgerät"],
  "basincli-yikama": ["pressure washers", "мойка высокого давления", "hochdruckreiniger"],
  "hava-kompresoru": ["air compressors", "компрессор", "kompressor"],
  kilit: ["door locks", "padlock", "замок", "schloss"],
  "akilli-kilit": ["smart locks", "fingerprint lock", "умный замок", "smartes türschloss"],
  musluk: ["faucets", "tap", "kitchen faucet", "смеситель", "wasserhahn", "armatur"],
  "alet-cantasi": ["tool bags", "сумка для инструментов", "werkzeugtasche"],
  "lehim-makinesi": ["soldering irons", "soldering station", "паяльник", "lötkolben"],
  "bahce-hortumu": ["garden hoses", "expandable hose", "шланг садовый", "gartenschlauch"],
  saksi: ["flower pots", "planters", "plant pot", "горшок для цветов", "blumentopf", "pot bunga"],
  "bahce-makasi": ["pruning shears", "garden shears", "секатор", "gartenschere"],
  tohum: ["seeds", "семена", "samen", "benih"],
  "cim-bicme-makinesi": ["lawn mowers", "газонокосилка", "rasenmäher"],
  "bahce-lambasi": ["solar lights", "garden lights", "solar garden lights", "садовый светильник", "solarleuchte"],
  hamak: ["hammocks", "гамак", "hängematte"],
  "bahce-mobilyasi": ["patio furniture", "garden furniture", "outdoor furniture", "садовая мебель", "gartenmöbel"],
  "sulama-sistemi": ["drip irrigation", "irrigation kit", "капельный полив", "tropfbewässerung"],
  "bocek-kovucu": ["mosquito repellent", "bug zapper", "insect killer", "отпугиватель комаров", "insektenvernichter"],
  mangal: ["bbq grills", "barbecue", "grill", "charcoal grill", "мангал", "гриль", "holzkohlegrill"],
  havuz: ["inflatable pools", "swimming pool", "kiddie pool", "бассейн", "planschbecken"],
  "yapi-bloklari": ["building blocks", "bricks", "lego compatible", "конструктор", "bausteine"],
  "uzaktan-kumandali-araba": ["rc cars", "remote control car", "радиоуправляемая машина", "ferngesteuertes auto"],
  "pelus-oyuncak": ["plush toys", "stuffed animal", "stuffed toy", "ぬいぐるみ", "인형", "мягкая игрушка", "plüschtier", "boneka"],
  puzzle: ["puzzles", "jigsaw puzzle", "пазл"],
  slime: ["slime", "слайм"],
  ucurtma: ["kites", "воздушный змей", "drachen"],
  "kutu-oyunu": ["board games", "card game", "настольная игра", "brettspiel"],
  "oyuncak-bebek": ["dolls", "baby doll", "кукла", "puppe"],
  "egitici-oyuncak": ["educational toys", "montessori toy", "learning toy", "развивающая игрушка", "lernspielzeug"],
  "model-araba": ["diecast", "model cars", "модель автомобиля", "modellauto"],
  figur: ["action figures", "figurine", "collectible figure", "フィギュア", "피규어", "фигурка"],
  "oyun-hamuru": ["play dough", "modeling clay", "пластилин", "knete"],
  "bilim-seti": ["science kits", "stem kit", "набор для опытов", "experimentierkasten"],
  trambolin: ["trampolines", "батут", "trampolin"],
  "cocuk-bisikleti": ["kids bikes", "children's bike", "balance bike", "детский велосипед", "kinderfahrrad"],
  "fidget-oyuncak": ["fidget toys", "pop it", "fidget spinner", "антистресс"],
  "bebek-arabasi": ["strollers", "pram", "pushchair", "buggy", "ベビーカー", "유모차", "коляска", "kinderwagen", "stroller bayi"],
  biberon: ["baby bottles", "feeding bottle", "哺乳瓶", "бутылочка для кормления", "babyflasche"],
  "bebek-kamerasi": ["baby monitors", "видеоняня", "babyphone"],
  kanguru: ["baby carriers", "baby wrap", "эрго рюкзак", "babytrage"],
  "oyun-mati": ["play mats", "baby mat", "развивающий коврик", "spielmatte"],
  "dis-kasiyici": ["teethers", "teething toy", "прорезыватель", "beißring"],
  "mama-sandalyesi": ["high chairs", "стульчик для кормления", "hochstuhl"],
  "bebek-bezi": ["diapers", "nappies", "подгузники", "windeln", "popok"],
  "islak-mendil": ["wet wipes", "baby wipes", "влажные салфетки", "feuchttücher"],
  emzik: ["pacifiers", "dummy", "soother", "пустышка", "schnuller"],
  "oto-koltugu": ["car seats", "booster seat", "автокресло", "kindersitz"],
  "bebek-besigi": ["cribs", "bassinet", "cot", "кроватка", "babybett"],
  "gogus-pompasi": ["breast pumps", "молокоотсос", "milchpumpe"],
  onluk: ["bibs", "слюнявчик", "lätzchen"],
  "kopek-tasmasi": ["dog leashes", "dog collar", "dog harness", "leash", "犬 リード", "поводок", "ошейник", "hundeleine", "hundehalsband"],
  "pet-yatagi": ["pet beds", "dog bed", "cat bed", "лежанка", "hundebett", "katzenbett"],
  "mama-kabi": ["pet feeders", "pet bowl", "automatic feeder", "миска для кошек", "futterautomat"],
  "kedi-tirmalama": ["cat scratchers", "scratching post", "cat tree", "когтеточка", "kratzbaum"],
  "pet-tasima-cantasi": ["pet carriers", "cat carrier", "переноска", "transportbox"],
  "pet-oyuncagi": ["pet toys", "dog toy", "cat toy", "игрушка для собак", "hundespielzeug"],
  "kedi-kumu": ["cat litter", "猫砂", "наполнитель для кошачьего туалета", "katzenstreu"],
  "kopek-mamasi": ["dog food", "корм для собак", "hundefutter"],
  "kedi-mamasi": ["cat food", "корм для кошек", "katzenfutter"],
  akvaryum: ["aquariums", "fish tank", "аквариум", "aquarium"],
  "jel-kalem": ["gel pens", "pens", "ballpoint pen", "ручка", "gelstift", "kugelschreiber"],
  defter: ["notebooks", "journal", "planner", "ノート", "тетрадь", "блокнот", "notizbuch", "buku catatan"],
  "yukselen-masa": ["standing desks", "height adjustable desk", "стол с регулировкой высоты", "höhenverstellbarer schreibtisch"],
  "ofis-koltugu": ["office chairs", "ergonomic chair", "gaming chair", "オフィスチェア", "офисное кресло", "bürostuhl"],
  "beyaz-tahta": ["whiteboards", "маркерная доска", "whiteboard"],
  "kagit-ogutucu": ["paper shredders", "шредер", "aktenvernichter"],
  makas: ["scissors", "ножницы", "schere"],
  "hesap-makinesi": ["calculators", "калькулятор", "taschenrechner"],
  "koli-bandi": ["packing tape", "packaging tape", "скотч", "klebeband"],
  "kargo-kutusu": ["shipping boxes", "cardboard box", "carton box", "mailing box", "картонная коробка", "versandkarton"],
  "balonlu-naylon": ["bubble wrap", "воздушно-пузырьковая пленка", "luftpolsterfolie"],
  "strec-film": ["stretch film", "stretch wrap", "стрейч пленка", "stretchfolie"],
  "etiket-yazici": ["label printers", "thermal printer", "shipping label printer", "термопринтер", "etikettendrucker"],
  "raf-sistemi": ["shelving", "storage rack", "shelf unit", "стеллаж", "regal"],
  "kagit-poset": ["paper bags", "kraft bag", "бумажные пакеты", "papiertüten"],
  "kilitli-poset": ["zip bags", "ziplock bags", "resealable bags", "zip lock", "зип пакеты", "druckverschlussbeutel"],
  "hediye-kutusu": ["gift boxes", "подарочная коробка", "geschenkbox"],
  kurdele: ["ribbons", "satin ribbon", "лента", "schleifenband"],
  "kargo-poseti": ["mailer bags", "poly mailers", "courier bags", "курьерские пакеты", "versandtaschen"],
  "barkod-etiketi": ["barcode labels", "thermal labels", "термоэтикетки", "etiketten"],
};

/**
 * Words that mark an accessory for another product ("kask askısı", "phone case for"). When a
 * title contains one and the matched leaf is not itself an accessory, the match is discounted.
 */
export const ACCESSORY_WORDS_FOLDED = new Set([
  "aski", "askisi", "aparat", "aparati", "aksesuar", "kilif", "kilifi", "tutucu", "tutucusu", "standi", "stand", "kapak", "kapagi", "cam", "cami", "lens", "lensi", "kayis", "kayisi",
  "yedek", "parca", "parcasi", "vizor", "vizoru", "sticker", "etiket", "koruyucu", "kilidi", "kilit", "cantasi", "kutusu", "adaptoru", "kablosu", "pili", "sarji", "filtresi", "filtre",
  "case", "cover", "holder", "mount", "strap", "visor", "sticker", "skin", "protector", "pouch", "sleeve", "bracket", "adapter", "cable", "replacement", "spare", "part", "parts", "accessory", "accessories",
]);
